# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=200)),
                ('a_url', models.URLField()),
                ('a_description', models.TextField()),
                ('a_pub_date', models.DateTimeField()),
                ('a_cluster', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('f_url', models.URLField()),
                ('f_region', models.CharField(max_length=200)),
                ('f_notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Feed'),
        ),
    ]
